# -*- ruby -*-
require 'rake'

task :default => :install

include FileUtils::Verbose

prefix = RbConfig::CONFIG['prefix']

dbdir = '/var/db/ranguba'
indexer = 'ranguba-indexer'
indexer_path = File.join("#{prefix}/bin", indexer)
cron_daily = '/etc/cron.daily/ranguba-indexer-update'
category_file = 'etc/ranguba/category.tsv'
category_path = File.join(prefix, category_file)
category_dir = File.dirname(category_path)

directory dbdir
directory category_dir

desc 'create empty category file stub'
task :category_path => category_path
file(category_path => category_dir) do |t|
  puts "create #{name = t.name}"
  open(name, 'w') do |f|
    f.puts "#URL""\t""TITLE"
  end
end

desc 'install daily cron job to update ranguba index'
task :cron_daily => cron_daily
file cron_daily do |t|
  puts "create #{name = t.name}"
  open(name, File::WRONLY|File::CREAT, 0755) do |f|
    f.puts <<EOF
#!/bin/sh
PREFIX="#{prefix}"
DBDIR="#{dbdir}"
PATH="$PREFIX/bin:$PATH"
cd "$PREFIX"
exec "ranguba-indexer" -c #{category_file} "$DBDIR/index.db"
EOF
  end
end

desc 'install indexer'
task :indexer => indexer_path
file indexer_path => indexer do |t|
  install(indexer, t.name)
end

desc 'install all'
task :install => [:cron_daily, :category_path, :indexer]

desc 'uninstall'
task :uninstall do
  rm_f([indexer_path, cron_daily, category_path])
  rmdir([category_dir, dbdir])
end
