#!/bin/sh

cd /home/ranguba/ranguba

RAILS_ENV=production
export RAILS_ENV

DBUS_LAUNCH=
if which dbus-launch > /dev/null; then
    DBUS_LAUNCH="dbus-launch --exit-with-session"
fi

$DBUS_LAUNCH /home/ranguba/bin/ruby /home/ranguba/ranguba/bin/ranguba-indexer
